---
default: profile0
profile0:
  vk0:
  - K_Z
  - K_RETURN
  - P_BUTTON0
  vk1:
  - K_X
  - K_ESCAPE
  - P_BUTTON1
  vk2:
  - K_LSHIFT
  - P_BUTTON2
  vk3:
  - K_A
  - P_BUTTON3
  vk4:
  - K_S
  - P_BUTTON4
  vk5:
  - K_D
  - P_BUTTON5
  vk6:
  - K_F
  - P_BUTTON6
  vk7:
  - K_G
  - P_BUTTON7
  vk8:
  - K_H
  - P_BUTTON8
  vk9:
  - K_J
  - P_BUTTON9
  vk10:
  - K_K
  - P_BUTTON10
  vk11:
  - K_L
  - P_BUTTON11
  vk12:
  - K_C
  - P_BUTTON12
  vk13:
  - K_V
  - P_BUTTON13
  vk14:
  - K_B
  - P_BUTTON14
  vk15:
  - K_N
  - P_BUTTON15
  vk_left:
  - K_LEFT
  - P_LEFT
  vk_up:
  - K_UP
  - P_UP
  vk_right:
  - K_RIGHT
  - P_RIGHT
  vk_down:
  - K_DOWN
  - P_DOWN
profile1:
  vk0:
  - K_C
  vk1:
  - K_X
  vk2:
  - K_LSHIFT
  vk3:
  - K_LCONTROL
  vk4:
  - K_Q
  vk5:
  - K_S
  vk6:
  - K_P
  vk7:
  - K_G
  vk8:
  - K_H
  vk9:
  - K_B
  vk10:
  - K_B
  vk11:
  - K_B
  vk12:
  - K_B
  vk13:
  - K_B
  vk14:
  - K_B
  vk15:
  - K_B
  vk_left:
  - K_LEFT
  - P_LEFT
  vk_up:
  - K_UP
  - P_UP
  vk_right:
  - K_RIGHT
  - P_RIGHT
  vk_down:
  - K_DOWN
  - P_DOWN
profile3:
  vk0:
  - P_BUTTON0
  vk1:
  - P_BUTTON1
  vk2:
  - P_BUTTON2
  vk3:
  - P_BUTTON3
  vk4:
  - P_BUTTON4
  vk5:
  - P_BUTTON5
  vk6:
  - P_BUTTON6
  vk7:
  - P_BUTTON7
  vk8:
  - P_BUTTON8
  vk9:
  - P_BUTTON9
  vk10:
  - P_BUTTON10
  vk11:
  - P_BUTTON11
  vk12:
  - P_BUTTON12
  vk13:
  - P_BUTTON13
  vk14:
  - P_BUTTON14
  vk15:
  - P_BUTTON15
  vk_left:
  - P_LEFT
  vk_up:
  - P_UP
  vk_right:
  - P_RIGHT
  vk_down:
  - P_DOWN
